### ISSUE TITLE
请问requirements.txt中为什么torch和torchvision有+cpu

### ISSUE THREAD

**Issue by Elsanna** [DCSong/CRNN-DenseNet#1]
请问requirements.txt中为什么torch和torchvision有+cpu？本项目是不是只能安装pytorch1.2.0和torchvision0.4.0的cpuonly版本呢？

**Comment by dechaosong** [comment]
requiremetns.txt中只列出了我的本地测试环境，其他的pytorch版本我没有测试过，不过应该是没问题，除非pytorch或torchvision去掉了某个API。另外，不管是训练还是测试，用GPU版本也是没问题的。
