### ISSUE TITLE
关于ICDAR2015数据集训练

### ISSUE THREAD

**Issue by Elsanna** [DCSong/CRNN-DenseNet#3]
您好，目前该项目是不是只适用于中文识别呢？如果想要进行英文数据集上的训练和测试（如ICDAR2015-task3数据集），需要进行哪些改动呢？谢谢！

**Comment by dechaosong** [comment]
之前使用的训练集包含了绝大部分中英文、标点符号和特殊字符，但是由于英文和中文间隔差距较大，容易出现漏掉英文字符的情况。如果要适用于纯英文情况，建议重新训练，只需要根据数据集修改num_classes之类的超参数即可

**Comment by Elsanna** [comment]
我读了代码发现在训练和测试过程中生成的标签有一个数字到中文字符的转换的过程，需要用到/Dataset/labels/Char2ldx.txt，用纯英文数据集训练和测试的话是否也需要类似的文件呢？

**Comment by dechaosong** [comment]
那是测试时用来将标签还原为原始字符的字典文件，与训练时将字符转化为标签的文件对应

**Comment by Elsanna** [comment]
对对，这个我明白，在我用纯英文数据集进行训练和测试的时候，是否也需要一对这样的转化文件呢？我看了一下ICDAR2015-task3的ground truth，其中gt.txt中是这样，word_1.png, "Genaxis Theatre"，但是coords.txt中是这样，word_1.png,0,0,86,0,88,13,1,13。

**Comment by dechaosong** [comment]
需要将字符转化为数字标签进行训练，数字标签的顺序可以自己定义。coords这是定位任务，与识别无关。

**Comment by Elsanna** [comment]
好的，谢谢~
