### ISSUE TITLE
why is the loss value negative? 

### ISSUE THREAD

**Issue by Kangjy1011** [DCSong/CRNN-DenseNet#6]
Hi, DCSong, 
I have appreciation of your code.
I have question about train. 
In my training my own data, loss value is negative.
Train Epoch: 1  Batch_Loss: -2.8431  Epoch_Loss: -3.5735  CER: 1.0000  SER: 1.0000: 100%|█| 386/386 [01:48<00:00,  3.54

why is the loss value negative? 
Please, I`d like to share your idea.

**Comment by dechaosong** [comment]
You could debug the code and review the data and label is or not the format you want as https://zhuanlan.zhihu.com/p/67415439.
What's more, the CTC is not easy to be convergent, you could let it train go on.
